version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: 33557788
      DB_NAME: controle_alimentacao
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "80:80"
    volumes:
      - .:/app  # Mapeia o diretório local para dentro do contêiner
    command: ["node", "server.js"]  # Comando para iniciar a aplicação

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 33557788
      POSTGRES_DB: controle_alimentacao
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mapeia o arquivo SQL para rodar na inicialização
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
